### PR TITLE
Re-added strongname signing.

### PR DESCRIPTION
**Pull request by hikarikuen**
Originally added in PR  #20 
Seems to have been removed in version 2.0.0.
Original issue #19

### CODE REVIEW

**Comment by hikarikuen** [comment]
@barnhill Would you be ok with adding strongname signing back in? My organization uses this library in a signed ClickOnce app and we aren't able to upgrade to versions > 2.0.0 because the signing was removed.

**Comment by barnhill** [comment]
@binki How do you feel about reintroducing this?  I think it should be ok.

**Comment by barnhill** [comment]
Added strong name signing of the assembly along with this major update: https://github.com/barnhill/barcodelib/pull/152

**Comment by barnhill** [comment]
Closing this issue in preparation of that PR to release

**Pull request closed without merging**
