### PR TITLE
Bump version for 1.3.1 release

### PR DESCRIPTION
**Pull request by marik91**
Not sure how you push this to nuget.org, but because of null exception we can not use latest version (1.3) while fix already done 5 months ago but do not released to nuget.org. So I hope by increasing version maybe you have automated process to push it to nuget repo ar at least it will make you see that we waiting for new release.

### CODE REVIEW

**Comment by barnhill** [comment]
Are you able to use a .net core lib? I was going to merge that pull I put out to upgrade it to a core and standard lib

**Comment by marik91** [comment]
we are on .NET 4.7.2 now, so if it's .NET Standard lib then we should be good to go

**Comment by barnhill** [comment]
Ive had this pull out for a while trying to get some community feedback.  Its a pretty big conversion but the same functionality.  Ill take a look at it as soon as I get home from work and parent teacher conferences tonight.

**Comment by barnhill** [comment]
@marik91 omg Im sorry I havent gotten to this yet.  Ive been working 14-15 hour days.

**Comment by barnhill** [comment]
bumping version to 2.0.0 and merging in the conversion to .net standard.  Keep me posted if you run into any issues.  Ill have the nuget posted here very shortly hopefully.

**Pull request closed without merging**
