### PR TITLE
Sign Assembly for use in COM dlls

### PR DESCRIPTION
**Pull request by WebsiteDeveloper**
@barnhill pull request for #19

### CODE REVIEW

**Comment by WebsiteDeveloper** [comment]
@barnhill ping

**Comment by barnhill** [comment]
@WebsiteDeveloper let me take a look at doing this but Id like to generate my own key I would think.

**Comment by WebsiteDeveloper** [comment]
Yeah probably

**Comment by barnhill** [comment]
I've created a new signing key and checked it in. Also I created a nuget package and uploaded that too.  Thank you for the contribution and I welcome more!!

**Comment by hikarikuen** [comment]
@barnhill Any chance you would be willing to add the signing back in to future 2.x.x versions? It appears versions since 2.0.0 are not signed.

**Pull request closed without merging**
