### PR TITLE
Update to 5.0.0 of System.Drawing.Common, Add JSON Serialization

### PR DESCRIPTION
**Pull request by barnhill**

### CODE REVIEW

**Comment by barnhill** [comment]
Fixes https://github.com/barnhill/barcodelib/issues/96

**Review by binki — APPROVED** [review]
It looks like you addressed the issue in #96. I have not done full due diligence in checking this change, but from what I read it looks good to me!

**Comment by barnhill** [comment]
Want me to wait for you to look at it closer or test it?

**Comment by binki** [comment]
> Want me to wait for you to look at it closer or test it?

No, I think you should just go ahead ;-).

**Comment by barnhill** [comment]
I'm still without internet at the house :(

Brad Barnhill, MSN, RN
bradbarnhill@hotmail.com

**Pull request merged**
